# Generated by Django 4.1.4 on 2022-12-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='complete',
        ),
        migrations.AddField(
            model_name='notes',
            name='Body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
